#!/usr/bin/env python3
"""Generate the runtime catalog for independently downloaded Dune2R art."""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path


DISPLAY_NAMES = {
    "gravel": "Gravel Terrain Remastered",
    "harkonnendevastator": "Harkonnen Devastator Remastered",
    "ordostank": "Ordos Tank Remastered",
    "refinery": "Atreides Refinery Remastered",
}


def git_revision(repo: Path, revision: str = "HEAD") -> str:
    return subprocess.check_output(
        ["git", "rev-parse", revision], cwd=repo, text=True
    ).strip()


def git_blob(repo: Path, revision: str, path: Path) -> bytes:
    relative = path.relative_to(repo).as_posix()
    return subprocess.check_output(["git", "show", f"{revision}:{relative}"], cwd=repo)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--revision", help="Immutable Git revision containing the assets")
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    repo = args.repo.resolve()
    revision = git_revision(repo, args.revision or "HEAD")
    units_root = repo / "mods" / "Dune2R" / "graphics_hd" / "units"
    output = args.output or repo / "mods" / "Dune2R" / "asset-catalog.ini"
    units = sorted(path for path in units_root.iterdir() if path.is_dir())

    lines = [
        "# Generated by scripts/generate-dune2r-asset-catalog.py",
        "# URLs are pinned to an immutable public game commit.",
        "[Catalog]",
        "Schema=1",
        f"Revision={revision}",
        "BaseURL=https://raw.githubusercontent.com/VR48/dunecity/"
        f"{revision}/mods/Dune2R/graphics_hd/units",
        f"PackCount={len(units)}",
        "",
    ]

    for pack_index, unit_dir in enumerate(units):
        files = sorted(
            path for path in unit_dir.rglob("*")
            if path.is_file() and path.name != ".gitkeep"
        )
        lines.extend(
            [
                f"[Pack.{pack_index}]",
                f"ID={unit_dir.name}",
                f"DisplayName={DISPLAY_NAMES.get(unit_dir.name, unit_dir.name)}",
                "Variant=remastered",
                f"Unit={unit_dir.name}",
                f"FileCount={len(files)}",
            ]
        )
        for file_index, path in enumerate(files):
            relative = path.relative_to(unit_dir).as_posix()
            blob = git_blob(repo, revision, path)
            digest = hashlib.sha256(blob).hexdigest()
            lines.append(f"File.{file_index}={relative}|{len(blob)}|{digest}")
        lines.append("")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="ascii", newline="\n")
    print(f"Wrote {output} with {len(units)} pack(s) pinned to {revision}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
